### ISSUE TITLE
backprojection missing csv file

### ISSUE THREAD

**Issue by guygastineau** [troymessina/Jupyter#1]
Hey Troy,

Is the `threeobjectexample.csv` file available anywhere? I can't get the notebook to function without it.

**Comment by troymessina** [comment]
threeobjectexample.csv is in the repository now.

**Comment by guygastineau** [comment]
Thank you.

**Comment by guygastineau** [comment]
Sweet it is all working now, so I can properly test the refactoring idea I had.
